/*
** ###################################################################
**     This code is generated by the Device Initialization Tool.
**     It is overwritten during code generation.
**     USER MODIFICATION ARE PRESERVED ONLY INSIDE INTERRUPT SERVICE ROUTINES
**     OR EXPLICITLY MARKED SECTIONS
**
**     Project     : DeviceInitialization
**     Processor   : MC9S08QE32CLC
**     Version     : Component 01.005, Driver 01.08, CPU db: 3.00.027
**     Datasheet   : MC9S08QE32RM Rev. 3 Draft A 11/2009
**     Date/Time   : 2014-12-17, 19:41, # CodeGen: 29
**     Abstract    :
**         This module contains device initialization code 
**         for selected on-chip peripherals.
**     Contents    :
**         Function "MCU_init" initializes selected peripherals
**
**     Copyright : 1997 - 2012 Freescale, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################
*/

/* MODULE MCUinit */

#include <mc9s08qe32.h>                /* I/O map for MC9S08QE32CLC */
#include "MCUinit.h"

/* Standard ANSI C types */
#ifndef int8_t
typedef signed char int8_t;
#endif
#ifndef int16_t
typedef signed int int16_t;
#endif
#ifndef int32_t
typedef signed long int int32_t;
#endif

#ifndef uint8_t
typedef unsigned char uint8_t;
#endif
#ifndef uint16_t
typedef unsigned int uint16_t;
#endif
#ifndef uint32_t
typedef unsigned long int uint32_t;
#endif

/* User declarations and definitions */
/*   Code, declarations and definitions here will be preserved during code generation */
#include "string.h"
#define TIMEOUT_VALUE	500

extern char datos_medidor_buffer[81];
extern char flag_recibido;
extern unsigned int secuencia;
extern int ventana_modbus;

/* End of user declarations and definitions */


/*
** ===================================================================
**     Method      :  MCU_init (component MC9S08QE32_32)
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/
void MCU_init(void)
{
  /* ### MC9S08QE32_32 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* Common initialization of the write once registers */
  /* SOPT1: COPE=0,COPT=1,STOPE=0,BKGDPE=1,RSTPE=0 */
  SOPT1 = 0x42U;                                   
  /* SPMSC1: LVDF=0,LVDACK=0,LVDIE=0,LVDRE=1,LVDSE=1,LVDE=1,BGBE=0 */
  SPMSC1 = 0x1CU;                                   
  /* SPMSC2: LPR=0,LPRS=0,LPWUI=0,PPDF=0,PPDACK=0,PPDE=1,PPDC=0 */
  SPMSC2 = 0x02U;                                   
  /* SPMSC3: LVDV=0,LVWV=0,LVWIE=0 */
  SPMSC3 &= (unsigned char)~(unsigned char)0x38U;                     
  /*  System clock initialization */
  /*lint -save  -e923 Disable MISRA rule (11.3) checking. */
  if (*(unsigned char*far)0xFFAFU != 0xFFU) { /* Test if the device trim value is stored on the specified address */
    ICSTRM = *(unsigned char*far)0xFFAFU; /* Initialize ICSTRM register from a non volatile memory */
    ICSSC = (unsigned char)((*(unsigned char*far)0xFFAEU) & (unsigned char)0x01U); /* Initialize ICSSC register from a non volatile memory */
  }
  /*lint -restore Enable MISRA rule (11.3) checking. */
  /* ICSC1: CLKS=0,RDIV=2,IREFS=0,IRCLKEN=0,IREFSTEN=0 */
  ICSC1 = 0x10U;                       /* Initialization of the ICS control register 1 */
  /* ICSC2: BDIV=1,RANGE=1,HGO=0,LP=0,EREFS=1,ERCLKEN=1,EREFSTEN=0 */
  ICSC2 = 0x66U;                       /* Initialization of the ICS control register 2 */
  while(ICSSC_OSCINIT == 0U) {         /* Wait until the initialization of the external crystal oscillator is completed */
  }
  /* ICSSC: DRST_DRS=0,DMX32=0 */
  ICSSC &= (unsigned char)~(unsigned char)0xE0U; /* Initialization of the ICS status and control */
  while((ICSSC & 0xC0U) != 0x00U) {    /* Wait until the FLL switches to Low range DCO mode */
  }

  /* SCGC1: TPM3=1,TPM2=1,TPM1=1,ADC=1,IIC=1,SCI2=1,SCI1=1 */
  SCGC1 = 0xFFU;                                   
  /* SCGC2: DBG=1,FLS=1,IRQ=1,KBI=1,ACMP=1,RTC=1,SPI=1 */
  SCGC2 = 0xFFU;                                   
  /* Common initialization of the CPU registers */
  /* PTASE: PTASE7=0,PTASE6=0,PTASE4=0,PTASE3=0,PTASE2=0,PTASE1=0,PTASE0=0 */
  PTASE &= (unsigned char)~(unsigned char)0xDFU;                     
  /* PTBSE: PTBSE7=0,PTBSE6=0,PTBSE5=0,PTBSE4=0,PTBSE3=0,PTBSE2=0,PTBSE1=0,PTBSE0=0 */
  PTBSE = 0x00U;                                   
  /* PTCSE: PTCSE7=0,PTCSE6=0,PTCSE5=0,PTCSE4=0,PTCSE3=0,PTCSE2=0,PTCSE1=0,PTCSE0=0 */
  PTCSE = 0x00U;                                   
  /* PTDSE: PTDSE3=0,PTDSE2=0,PTDSE1=0,PTDSE0=0 */
  PTDSE &= (unsigned char)~(unsigned char)0x0FU;                     
  /* PTADS: PTADS7=0,PTADS6=0,PTADS5=0,PTADS4=0,PTADS3=0,PTADS2=0,PTADS1=0,PTADS0=0 */
  PTADS = 0x00U;                                   
  /* PTBDS: PTBDS7=0,PTBDS6=0,PTBDS5=0,PTBDS4=0,PTBDS3=0,PTBDS2=0,PTBDS1=0,PTBDS0=0 */
  PTBDS = 0x00U;                                   
  /* PTCDS: PTCDS7=0,PTCDS6=0,PTCDS5=0,PTCDS4=0,PTCDS3=0,PTCDS2=0,PTCDS1=0,PTCDS0=0 */
  PTCDS = 0x00U;                                   
  /* PTDDS: PTDDS7=0,PTDDS6=0,PTDDS5=0,PTDDS4=0,PTDDS3=0,PTDDS2=0,PTDDS1=0,PTDDS0=0 */
  PTDDS = 0x00U;                                   
  /* ### Init_GPIO init code */
  /* PTAD: PTAD3=0,PTAD2=0,PTAD1=0 */
  PTAD &= (unsigned char)~(unsigned char)0x0EU;                     
  /* PTADD: PTADD3=1,PTADD2=1,PTADD1=1 */
  PTADD |= (unsigned char)0x0EU;                      
  /* ### Init_SCI init code */
  /* SCI1C2: TIE=0,TCIE=0,RIE=0,ILIE=0,TE=0,RE=0,RWU=0,SBK=0 */
  SCI1C2 = 0x00U;                      /* Disable the SCI1 module */
  (void)(SCI1S1 == 0U);                /* Dummy read of the SCI1S1 register to clear flags */
  (void)(SCI1D == 0U);                 /* Dummy read of the SCI1D register to clear flags */
  /* SCI1S2: LBKDIF=1,RXEDGIF=1,RXINV=0,RWUID=0,BRK13=0,LBKDE=0,RAF=0 */
  SCI1S2 = 0xC0U;                                   
  /* SCI1BDH: LBKDIE=0,RXEDGIE=0,SBR12=0,SBR11=0,SBR10=0,SBR9=0,SBR8=0 */
  SCI1BDH = 0x00U;                                   
  /* SCI1BDL: SBR7=0,SBR6=0,SBR5=0,SBR4=1,SBR3=1,SBR2=1,SBR1=0,SBR0=1 */
  SCI1BDL = 0x1DU;                                   
  /* SCI1C1: LOOPS=0,SCISWAI=0,RSRC=0,M=0,WAKE=0,ILT=0,PE=0,PT=0 */
  SCI1C1 = 0x00U;                                   
  /* SCI1C3: R8=0,T8=0,TXDIR=1,TXINV=0,ORIE=0,NEIE=0,FEIE=0,PEIE=0 */
  SCI1C3 = 0x20U;                                   
  /* SCI1C2: TIE=0,TCIE=0,RIE=1,ILIE=0,TE=1,RE=1,RWU=0,SBK=0 */
  SCI1C2 = 0x2CU;                                   
  /* ### Init_SCI init code */
  /* SCI2C2: TIE=0,TCIE=0,RIE=0,ILIE=0,TE=0,RE=0,RWU=0,SBK=0 */
  SCI2C2 = 0x00U;                      /* Disable the SCI2 module */
  (void)(SCI2S1 == 0U);                /* Dummy read of the SCI2S1 register to clear flags */
  (void)(SCI2D == 0U);                 /* Dummy read of the SCI2D register to clear flags */
  /* SCI2S2: LBKDIF=1,RXEDGIF=1,RXINV=0,RWUID=0,BRK13=0,LBKDE=0,RAF=0 */
  SCI2S2 = 0xC0U;                                   
  /* SCI2BDH: LBKDIE=0,RXEDGIE=0,SBR12=0,SBR11=0,SBR10=0,SBR9=0,SBR8=0 */
  SCI2BDH = 0x00U;                                   
  /* SCI2BDL: SBR7=0,SBR6=0,SBR5=0,SBR4=1,SBR3=1,SBR2=0,SBR1=1,SBR0=0 */
  SCI2BDL = 0x1AU;                                   
  /* SCI2C1: LOOPS=0,SCISWAI=0,RSRC=0,M=0,WAKE=0,ILT=0,PE=0,PT=0 */
  SCI2C1 = 0x00U;                                   
  /* SCI2C3: R8=0,T8=0,TXDIR=1,TXINV=0,ORIE=0,NEIE=0,FEIE=0,PEIE=0 */
  SCI2C3 = 0x20U;                                   
  /* SCI2C2: TIE=0,TCIE=0,RIE=1,ILIE=0,TE=1,RE=1,RWU=0,SBK=0 */
  SCI2C2 = 0x2CU;                                   
  /* ### Init_TPM init code */
  /* TPM1SC: TOF=0,TOIE=0,CPWMS=0,CLKSB=0,CLKSA=0,PS2=0,PS1=0,PS0=0 */
  TPM1SC = 0x00U;                      /* Stop and reset counter */
  TPM1MOD = 0xFFFFU;                   /* Period value setting */
  (void)(TPM1SC == 0U);                /* Overflow int. flag clearing (first part) */
  /* TPM1SC: TOF=0,TOIE=0,CPWMS=0,CLKSB=0,CLKSA=1,PS2=0,PS1=0,PS0=0 */
  TPM1SC = 0x08U;                      /* Int. flag clearing (2nd part) and timer control register setting */
  /* ### Init_GPIO init code */
  /* PTDD: PTDD2=0 */
  PTDD &= (unsigned char)~(unsigned char)0x04U;                     
  /* PTDDD: PTDDD2=1 */
  PTDDD |= (unsigned char)0x04U;                      
  /* ### Init_GPIO init code */
  /* PTCD: PTCD5=0,PTCD3=0,PTCD2=0,PTCD1=1,PTCD0=1 */
  PTCD = (PTCD & (unsigned char)~(unsigned char)0x2CU) | (unsigned char)0x03U;
  /* PTCPE: PTCPE5=0,PTCPE1=1,PTCPE0=1 */
  PTCPE = (PTCPE & (unsigned char)~(unsigned char)0x20U) | (unsigned char)0x03U;
  /* PTCDD: PTCDD5=1,PTCDD3=1,PTCDD2=1,PTCDD1=0,PTCDD0=0 */
  PTCDD = (PTCDD & (unsigned char)~(unsigned char)0x03U) | (unsigned char)0x2CU;
  /* ### Init_GPIO init code */
  /* PTBD: PTBD5=0,PTBD4=0,PTBD3=1,PTBD2=1 */
  PTBD = (PTBD & (unsigned char)~(unsigned char)0x30U) | (unsigned char)0x0CU;
  /* PTBPE: PTBPE3=1,PTBPE2=1 */
  PTBPE |= (unsigned char)0x0CU;                      
  /* PTBDD: PTBDD5=1,PTBDD4=1,PTBDD3=0,PTBDD2=0 */
  PTBDD = (PTBDD & (unsigned char)~(unsigned char)0x0CU) | (unsigned char)0x30U;
  /* ### Init_TPM init code */
  /* TPM2SC: TOF=0,TOIE=0,CPWMS=0,CLKSB=0,CLKSA=0,PS2=0,PS1=0,PS0=0 */
  TPM2SC = 0x00U;                      /* Stop and reset counter */
  TPM2MOD = 0xC350U;                   /* Period value setting */
  (void)(TPM2SC == 0U);                /* Overflow int. flag clearing (first part) */
  /* TPM2SC: TOF=0,TOIE=1,CPWMS=0,CLKSB=0,CLKSA=1,PS2=1,PS1=0,PS0=1 */
  TPM2SC = 0x4DU;                      /* Int. flag clearing (2nd part) and timer control register setting */
  /* ### Init_ADC init code */
  /* APCTL1: ADPC7=0,ADPC6=0,ADPC5=0,ADPC4=0,ADPC3=0,ADPC2=0,ADPC1=0,ADPC0=0 */
  APCTL1 = 0x00U;                                   
  /* ADCCFG: ADLPC=0,ADIV1=0,ADIV0=0,ADLSMP=0,MODE1=0,MODE0=1,ADICLK1=0,ADICLK0=0 */
  ADCCFG = 0x04U;                                   
  /* ADCCV: ADCV11=0,ADCV10=0,ADCV9=0,ADCV8=0,ADCV7=0,ADCV6=0,ADCV5=0,ADCV4=0,ADCV3=0,ADCV2=0,ADCV1=0,ADCV0=0 */
  ADCCV = 0x00U;                            
  /* ADCSC2: ADACT=0,ADTRG=0,ACFE=0,ACFGT=0 */
  ADCSC2 = 0x00U;                                   
  /* ADCSC1: COCO=0,AIEN=0,ADCO=0,ADCH4=0,ADCH3=0,ADCH2=0,ADCH1=0,ADCH0=0 */
  ADCSC1 = 0x00U;                                   
  /* ### */
  /*lint -save  -e950 Disable MISRA rule (1.1) checking. */
  asm CLI;                             /* Enable interrupts */
  /*lint -restore Enable MISRA rule (1.1) checking. */

} /*MCU_init*/


/*lint -save  -e765 Disable MISRA rule (8.10) checking. */
/*
** ===================================================================
**     Interrupt handler : isrVsci2tx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVsci2tx(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVsci2tx */


/*
** ===================================================================
**     Interrupt handler : isrVsci2rx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVsci2rx(void)
{
    SCI2C2_RIE=0;
    (void)(SCI2S1_RDRF==0);
    datos_medidor_buffer[secuencia]=(unsigned char)SCI2D;
    secuencia++;	

    flag_recibido=1;
    SCI2C2_RIE=1;    
}
/* end of isrVsci2rx */


/*
** ===================================================================
**     Interrupt handler : isrVsci2err
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVsci2err(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVsci2err */


/*
** ===================================================================
**     Interrupt handler : isrVadc
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVadc(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVadc */


/*
** ===================================================================
**     Interrupt handler : isrVsci1tx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVsci1tx(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVsci1tx */


/*
** ===================================================================
**     Interrupt handler : isrVsci1rx
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVsci1rx(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVsci1rx */


/*
** ===================================================================
**     Interrupt handler : isrVsci1err
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVsci1err(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVsci1err */


/*
** ===================================================================
**     Interrupt handler : isrVtpm2ovf
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVtpm2ovf(void)
{
    TPM2SC_TOIE=0;
    ventana_modbus=1;
    (void)(TPM2SC == 0);
    TPM2SC_TOF=0;
    TPM2SC_TOIE=1;	
}
/* end of isrVtpm2ovf */


/*
** ===================================================================
**     Interrupt handler : isrVtpm1ovf
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVtpm1ovf(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVtpm1ovf */


/*
** ===================================================================
**     Interrupt handler : isrVlvd
**
**     Description :
**         User interrupt service routine. 
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
__interrupt void isrVlvd(void)
{
  /* Write your interrupt code here ... */

}
/* end of isrVlvd */


/*lint -restore Enable MISRA rule (8.10) checking. */

/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
/* Initialization of the CPU registers in FLASH */
/* NVPROT: FPS7=1,FPS6=1,FPS5=1,FPS4=1,FPS3=1,FPS2=1,FPS1=1,FPDIS=1 */
static const unsigned char NVPROT_INIT @0x0000FFBDU = 0xFFU;
/* NVOPT: KEYEN=0,FNORED=1,SEC01=1,SEC00=0 */
static const unsigned char NVOPT_INIT @0x0000FFBFU = 0x7EU;
/*lint -restore Enable MISRA rule (1.1) checking. */



extern near void _Startup(void);

/* Interrupt vector table */
#ifndef UNASSIGNED_ISR
  #define UNASSIGNED_ISR ((void(*near const)(void)) 0xFFFF) /* unassigned interrupt service routine */
#endif

/*lint -save  -e923 Disable MISRA rule (11.3) checking. */
/*lint -save  -e950 Disable MISRA rule (1.1) checking. */
static void (* near const _vect[])(void) @0xFFC0 = { /* Interrupt vector table */
/*lint -restore Enable MISRA rule (1.1) checking. */
         UNASSIGNED_ISR,               /* Int.no. 31 Vtpm3ovf (at FFC0)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 30 Vtpm3ch5 (at FFC2)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 29 Vtpm3ch4 (at FFC4)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 28 Vtpm3ch3 (at FFC6)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 27 Vtpm3ch2 (at FFC8)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 26 Vtpm3ch1 (at FFCA)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 25 Vtpm3ch0 (at FFCC)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 24 Vrtc (at FFCE)                  Unassigned */
         isrVsci2tx,                   /* Int.no. 23 Vsci2tx (at FFD0)               Used */
         isrVsci2rx,                   /* Int.no. 22 Vsci2rx (at FFD2)               Used */
         isrVsci2err,                  /* Int.no. 21 Vsci2err (at FFD4)              Used */
         UNASSIGNED_ISR,               /* Int.no. 20 Vacmpx (at FFD6)                Unassigned */
         isrVadc,                      /* Int.no. 19 Vadc (at FFD8)                  Used */
         UNASSIGNED_ISR,               /* Int.no. 18 Vkeyboard (at FFDA)             Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 17 Viic (at FFDC)                  Unassigned */
         isrVsci1tx,                   /* Int.no. 16 Vsci1tx (at FFDE)               Used */
         isrVsci1rx,                   /* Int.no. 15 Vsci1rx (at FFE0)               Used */
         isrVsci1err,                  /* Int.no. 14 Vsci1err (at FFE2)              Used */
         UNASSIGNED_ISR,               /* Int.no. 13 Vspi (at FFE4)                  Unassigned */
         UNASSIGNED_ISR,               /* Int.no. 12 VReserved12 (at FFE6)           Unassigned */
         isrVtpm2ovf,                  /* Int.no. 11 Vtpm2ovf (at FFE8)              Used */
         UNASSIGNED_ISR,               /* Int.no. 10 Vtpm2ch2 (at FFEA)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  9 Vtpm2ch1 (at FFEC)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  8 Vtpm2ch0 (at FFEE)              Unassigned */
         isrVtpm1ovf,                  /* Int.no.  7 Vtpm1ovf (at FFF0)              Used */
         UNASSIGNED_ISR,               /* Int.no.  6 Vtpm1ch2 (at FFF2)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  5 Vtpm1ch1 (at FFF4)              Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  4 Vtpm1ch0 (at FFF6)              Unassigned */
         isrVlvd,                      /* Int.no.  3 Vlvd (at FFF8)                  Used */
         UNASSIGNED_ISR,               /* Int.no.  2 Virq (at FFFA)                  Unassigned */
         UNASSIGNED_ISR,               /* Int.no.  1 Vswi (at FFFC)                  Unassigned */
         _Startup                      /* Int.no.  0 Vreset (at FFFE)                Reset vector */
};
/*lint -restore Enable MISRA rule (11.3) checking. */




/* END MCUinit */

/*
** ###################################################################
**
**     This file was created by Processor Expert 10.0 [05.03]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
